### ISSUE TITLE
Submission to UNESCO call for Examples of Open Science

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMycetoma/Talks-Meetings-Publicity#2]
The UNESCO call is [here](https://en.unesco.org/feedback/unescos-global-call-best-practices-open-science). 

Below is some suggested text for the freeform questions. Let me know of any edits **_in the next 24 h_**. Sorry. Will put myself as contact unless anyone else wants to be.

Ping @OpenSourceMycetoma/corecontrib 

UNESCO MycetOS Submission:
Q10 (300 words)

What are the key activities/components of the practice?
Open Source Mycetoma (MycetOS) carries out early stage drug discovery for the neglected tropical disease (NTD), mycetoma. Most of the activity involves taking molecules that are in the public domain and which have some antifungal potential, and improving those molecules through a combination of chemical and biological research. Through the licence governing the consortium (CC-BY-4.0) all researchers are able to contribute to any aspect of the project as equal participants. Day to day operations are governed by several “laws” (described in 10.1002/cmdc.201900565) that help to clarify that all data and ideas should be shared publicly in real time and that no patents will be taken. Additional activities include generating project ideas, seeking project inputs from others and collaborative paper writing.

What problems/issues/challenges does it address? 
The discovery and development of new, effective, inexpensive medicines for the treatment of the fungal NTD mycetoma. New medicines are sorely needed since presently there are no effective treatments and many patients suffer amputation.

What are the changes that resulted from the practice?
MycetOS has been in operation since ca 2015. It has, through publications (e.g. 10.1371/journal.pntd.0006437) and outreach activities (e.g. https://youtu.be/UeOtQJkECcs), shown how open source can lead to enhanced research outcomes in drug discovery. 

How does the practice benefit to the research community and/or broader society?
The commitment to open data ensures that all researchers can either compete with MycetOS, join the effort, or continue projects that are deprioritised. By actively carrying out this new way of working, we help to stimulate the discussion of how to translate IP-free molecules for the benefit of patients. We provide a simple route for the involvement of junior researchers or those from non-traditional backgrounds and have strong backing from an NGO (The Drugs for Neglected Diseases initiative).

Q11 - Replicability (100 words)
The consortium is replicable (it is itself a partial replica of Open Source Malaria) because:
1) the approach is governed by a simple, robust licence with simple rules and
2) the technical platform required to work in this way uses software that is either freely available (e.g. Github, Twitter) or generic (e.g. where there are numerous paid/free solutions, such as Labarchives (lab notebook), spreadsheet/data solutions (e.g. Google office), Zoom (public meetings)). Any researcher can employ their own solution, provided it aligns with the full data sharing policy.
3) Peer-reviewed publications help to acknowledge, formally, the contributors.
4) Funding agencies find the data sharing and inclusivity attractive.

Q12 Cost (50 words)
The consortium works faster if there is core funding, e.g. a postdoctoral researcher can help to leverage significant in-kind contributions through their work. To date MycetOS has been in receipt of little direct funding (mycetoma is neglected) and the community has had to grow organically and has included contributions from staff employed on other grants.

Q13  (200 words)
The preliminary impact of the project has been to gather together a committed community of researchers interested in the radically open sharing of their work towards new medcines, and who have demonstrably contributed their work/time/molecules. This has been simple to evaluate because, obviously, the contributions are made by people who interact with the project and whose identities are known. Contributions are either spontaneous (through the project being discovered via search engines or social media) or come from solicitations (consortium reaching out to people). Traditional impact is measured and evaluated via traditional peer-reviewed publications (e.g., 10.1371/journal.pntd.0010159). Sociologically, it has been clearly demonstrated that people contribute spontaneously because the project is completely open, i.e. that researchers know that their contributions will help the project and are still needed. It is also clear that the contributions are almost always of a high quality, from experts not necessarily known to the project core at the outset. MycetOS has obtained a small grant from the Royal Society in the UK to work on molecule synthesis with 17-year old students at a local school, who expressed the clear view that participating in the project made them more likely to study science further.

**Comment by wwjvdsande** [comment]
@mattodd 
On the website we always use the startdate of 2018. May be best to use that here as well. That was the date when the github page was launched. For the rest the text looks fine. You can be the contact person as far as I'm concerned. You are the pioneer in open drug discovery.

**Comment by bebi78** [comment]
@mattodd Because it's a UN organisation, maybe it should be added that scientists/institutes from almost all continents contribute or contributed to the project.

**Comment by bebi78** [comment]
@mattodd Good luck! BTW, I asked @bendndi last year to provide me with DNDi certificates of participation for my two undergraduate students who contributed to the DNDi OSN P1Tc and P8 projects, and Ben gratefully sent me two signed official DNDi certificates. Both of my students could use the certificates well for their applications. Maybe an official MycetOS certificate that can be delivered to participating pupils of grammar/high schools and undergraduate students might be a good idea to attract pupils and undergraduate students who are interested in medicinal chemistry.

**Comment by mattodd** [comment]
HI @bebi78 it's an interesting idea, thanks. Two arguments against: 1) there is an associated overhead of someone needing to do this, and we have no "staff" as such. We'd need volunteers to issue such things. 2) The evidence of participation should, if the project is online, _be online_. i.e. for CVs etc, it should be possible to link directly to the participation in the project, rather than a separate document that attests to the participation. I know that I would be much more impressed by an applicant who shows me what they have done rather than one who tells me about what they have done.

Am closing this Issue because the UNESCO submission was done, with Wendy as corresponding.
